### ISSUE TITLE
Auto minimize through task scheduler

### ISSUE THREAD

**Issue by DesNZ** [a-sync/audio-router#4]
Is there a way to have this minimized to tray automatically?

I have tried /min as well as /background to no avail. I would do it myself but me and C aren't exactly on good terms right now! /s

Thanks,
Firelfy!

**Comment by a-sync** [comment]
Not implemented atm. You can create a shortcut to start the program minimized. It won't bring up the app window, but it will be on the task bar and not in the tray.  ![shortcut starting minimized](https://i.stack.imgur.com/KHnO6.png)

**Comment by a-sync** [comment]
@Firelfy i created a new release (v0.10.5) which instead of opening the window, and adding it to the task bar, checks for the */min* option in the calling arguments and the *Minimized* shortcut option, and if one or both are present when starting the app it only creates the tray menu icon.

https://github.com/a-sync/audio-router/releases/tag/v0.10.5
